import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import adminApi from '@/services/adminApi';

const blank = { title: '', description: '', occasion: '', discount: '', startsAt: '', endsAt: '', enabled: true };
const toLocal = (date) => date ? new Date(date).toISOString().slice(0, 16) : '';
export default function AdminSales() {
  const [sales, setSales] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null);
  const load = () => adminApi.listSales().then((data) => setSales(data.sales)).catch(() => toast.error('Could not load sales'));
  useEffect(load, []);
  const save = async (e) => { e.preventDefault(); try { if (editing) await adminApi.updateSale(editing, form); else await adminApi.createSale(form); setEditing(null); setForm(blank); load(); toast.success('Sale saved'); } catch (err) { toast.error(err.response?.data?.message || 'Could not save sale'); } };
  const edit = (sale) => { setEditing(sale._id); setForm({ ...sale, startsAt: toLocal(sale.startsAt), endsAt: toLocal(sale.endsAt) }); };
  return <div className="max-w-5xl space-y-8"><div><p className="eyebrow mb-2">Campaigns</p><h1 className="heading-display text-3xl">Sale Management</h1></div>
    <form onSubmit={save} className="glass p-5 grid md:grid-cols-2 gap-4"><input required placeholder="Sale title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="admin-input"/><input required placeholder="Discount (e.g. Up to 25% off)" value={form.discount} onChange={(e) => setForm({ ...form, discount: e.target.value })} className="admin-input"/><input placeholder="Reason / occasion" value={form.occasion} onChange={(e) => setForm({ ...form, occasion: e.target.value })} className="admin-input"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })}/> Enabled</label><textarea placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="admin-input md:col-span-2"/><label className="text-sm text-ivory/60">Start<input required type="datetime-local" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} className="admin-input mt-1"/></label><label className="text-sm text-ivory/60">End<input required type="datetime-local" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} className="admin-input mt-1"/></label><div className="md:col-span-2 flex gap-3"><button className="px-5 py-3 bg-gold text-obsidian text-xs uppercase tracking-wide">{editing ? 'Update sale' : 'Create sale'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(blank); }} className="px-5 py-3 border border-gold/25 text-xs uppercase">Cancel</button>}</div></form>
    <div className="space-y-3">{sales.map((sale) => <div key={sale._id} className="glass p-4 flex flex-wrap gap-4 items-center justify-between"><div><p className="font-display text-xl">{sale.title}</p><p className="text-xs text-ivory/50">{sale.occasion || 'No occasion'} · {sale.discount} · {new Date(sale.startsAt).toLocaleString()} — {new Date(sale.endsAt).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={() => edit(sale)} className="text-xs text-gold">Edit</button><button onClick={async () => { if (window.confirm('Delete this sale?')) { await adminApi.deleteSale(sale._id); load(); } }} className="text-xs text-ember-light">Delete</button></div></div>)}</div></div>;
}
